- sections/ranges.include
Use is for comparisons. Leave equals for isEqualNode()
> Fix #33:  Use "is" for comparisons, Leave "equals" for isEqualNode()

- sections/nodes.include
Since 'unenumable' keyword is not valid in new WebIDL spec,
remove the reference in DOM spec.
> Fix #93: drop 'unenumable' for 'supported property names'.

- sections/nodes.include
Changes in Attr.
.nodeName is still being used. It's an alias of .name attribute.
> Fix #35: bring the legacy .nodeName for interface Attr.

- sections/nodes.include
Changes in Node & Document.
The attributes related to base URL are not optional and
should be type of USVString instead of DOMString. Use
the normalized name by following the HTML spec.
> Fix #27: base URL is not optional and type of USVString.

- sections/nodes.include
Changes in Document.
Instead of listing encoding names, reference the w3c encoding spec.
For the legacy use, bring .charset and inputEncoding into Document.
> Fix #30: Use encoding spec for reference.

- sections/events.include
Add a note for Event.isTrusted to clarify that mouse click event
generated by a user is trusted though historically its isTrusted
attribute is initialized to false.
> Fix #78: Clarify isTrusted

- sections/nodes.include
Changed in 3.4.Interface Node.
Cleanup nodeType and nodeName getter attribute's description.
Also change nodeType's list style to be similarly to nodeName.
> Fix #83: Cleanup nodeType algorithm a bit.

- sections/nodes.include
Queuing of mutation records looks inconsistent. To replace a child with
node within a parent, the mutation record should be queued after the
removal of child and insertion of node.
See https://github.com/whatwg/dom/pull/60 for more details.
> Fix #39: Part I: Always queue mutation records after said mutations.

- sections/nodes.include
- sections/terminology.include
Changes in Terminology & Node.
1.Group common selectors algorithms to add a note that
namespaces are not planned.
2.Comment out "match a relative selectors string" since it
is not being used.
> Fix #36: two changes on Selectors.

- sections/nodes.include
- sections/traversal.include
Changes in Attr, Node, Element, DOMCore, NodeFilter.
1. Make Attr inherit from Node again so there is a type node called
attribute node.
2. Related changes in several algorithms since Node has a new type
'ATTRIBUTE_NODE'. Need to consider this condition.
> Fix #77: Make Attr inherit from Node again.

- sections/nodes.include
Changes in Document.
1. Apply adopting steps only if documents are changed.
2. Recursively call for inclusive descendants.
Don't change custome element related changes.
> Fix #29: refine the steps of adopting a node for Document.

- sections/ranges.include
Changes in Range.
Refinements on the description from 'clone a range' to 'clone the
contents of a range'.
> Fix #44: change the description of 'cloning a range'.

- sections/nodes.include
Changes in mutation algorithm: ensure pre-insertion validity.
When parent is a document, it's necessary to do child checking
when doing preceding operation on it.
> Fix #26: check child is not null for preceding operation.

- sections/nodes.include
Several fixes in the procedure of 'replace a node':
1. Do not remove child from its parent when replacing a node by itself
2. Record previous silibing before doing 'adopt a node'.
3. Collect the node's children before doing 'insert a node'.
4. Other formats and reference errors.
> Fix #25: adjustments for 'replace a node' in mutation algorithms.

- sections/nodes.include
Changes in 'queuing a mutation record'.
1. 'Continue' is not clearly described. Use the combination of conditional
checkings to run substeps instead of the 'continue'.
2. Fix the link error of 'MutationRecord.type|target'.
It's from https://github.com/whatwg/dom/commit/d3653ac.
> Fix #42: Reword queue a mutation record to avoid "continue".

- sections/nodes.include
Changes in NamedNodeMap.
1. Add the interface of NamedNodeMap.
2. Omit duplicated items and non-lowercase property names.
3. NamedNodeMap supports IndexedProperties.
4. Since NamedNodeMap depends on the procedures of 'replace an attriubte'
and 'set an attribute', add them in the part of 'Element'.
> Fix #28: introduce NamedNodeMap into 4.1.

- sections/nodes.include
Changes in Node.
WebIDL introduces getter/setter, so use the description of
'getter/setter' for the interface Node's attributes.
> Fix #40: add getter/setter accessors of Node's attributes.

- sections/events.include
Changes in Events
Add explain of events cannot cause actions, just notification
> Fix #31: Explain events cannot cause actions, just notification

- index.bs
- sections/events.include
- sections/nodes.include
- sections/ranges.include
- sections/sets.include
> several fixes

- sections/nodes.include
Changes in Element.
Replace 'an attribute is set and an attribute is changed' with
'attribute change steps' for one shot procedure.
Also refine the description about the id of Element.
> Fix #139: Use a single concept for attribute change steps.

- index.bs
- sections/conformance.include
- sections/events.include
- sections/historical.include
- sections/nodes.include
- sections/ranges.include
- sections/sets.include
- sections/terminology.include
- sections/traversal.include
Changes for references, formats and grammer issues, like:
1, Move hyperlinks into index.bs.
2, Use HTML5.1 as link reference instead of HTML5.
3, Remove incorrect multiple definitions.
4, Use 'method', 'attribute' for dfn of interface, so that they
can be processed with correct links.
5, Add the description of 'when invoked' for each method of interface.
6, Follow the rule of 'getter' and 'setter' of WebIDL for the attributes
of Interface.
7, Use <a type> for Name, QName and Char instead of copying many
links.
8, So many other fixes for warnings/errors reported by the
'bikeshed' tool.
> Fix #76: clean up several grammar issues.

- index.bs
- sections/nodes.include
- sections/ranges.include
- sections/sets.include
- sections/terminology.include
1. Refer HTML51 instead of old versions.
2. Return the empty string otherwise for 'ordered set serializer'.
3. Remove quotes for kinds of DOM exceptions & errors.
4. Change the description of stringifier steps of Range
to 'stringification behavior' for linking.
5. Use 'current global object' and 'window's associated document'
from HTML5.1.
6. Remove the 9th step of 'split a Text node' for it's has been done
in 'Replace data with node'.
7. Correct the definition of Element's qualified name and their
references.
8. Add the 'context object' for attributes' getter.
9. Bring 'throw errors' for ChildNode.replaceWith() method.
10. Correct the references of attributes of MutationObserverInit.
> Fix #144: editorial for several sections.

- sections/nodes.include
Changes in Nodes/Document/Event.
1, remove ',' after if.
2, Replace 'can' with 'ought to'.
3, Set root to root for createTreeWalker and createNodeIterator.
> Fix #86: minor changes about description.

- index.bs
- sections/events.include
Use the relevant realm of the event target when firing an event.
Also note the difference between firing and dispatching an event.
> Fix #10: introduce firing an event

- sections/nodes.include
- add the concept `document tree`;
- to clarify the terms `in a document`, `in a document tree`, and `in a shadow tree`, which helps to fix #13 ;
- no test needed.
> add document tree
